---
name: on_hello_event1
pack: test_pack
description: Sample rule firing on test_pack.event1.
enabled: true
trigger:
    type: test_pack.event1
action:
    ref: test_pack.test_pack
    parameters:
        url: Yo
